const responseData = {
  users: [
    {
      userId: "a1b2c3d4",
      userName: "John Smith",
      userPhoneNumber: "123-456-7890",
      emailAddress: "john.smith@example.com",
      sex: "Male",
      age: 34,
      highestLevelOfEducation: "Bachelor's Degree",
      yearlyIncome: 85000,
      eventChoice: "Sporting Event",
    },
    {
      userId: "e5f6g7h8",
      userName: "Jane Doe",
      userPhoneNumber: "234-567-8901",
      emailAddress: "jane.doe@example.com",
      sex: "Female",
      age: 45,
      highestLevelOfEducation: "Master's Degree",
      yearlyIncome: 110000,
      eventChoice: "Theatrical Performance",
    },
    {
      userId: "i9j0k1l2",
      userName: "Peter Jones",
      userPhoneNumber: "345-678-9012",
      emailAddress: "peter.jones@example.com",
      sex: "Male",
      age: 22,
      highestLevelOfEducation: "High School Diploma",
      yearlyIncome: 42000,
      eventChoice: "Music Concert",
    },
    {
      userId: "m3n4o5p6",
      userName: "Mary Johnson",
      userPhoneNumber: "456-789-0123",
      emailAddress: "mary.johnson@example.com",
      sex: "Female",
      age: 51,
      highestLevelOfEducation: "PhD",
      yearlyIncome: 135000,
      eventChoice: "Comedy Show",
    },
    {
      userId: "q7r8s9t0",
      userName: "David Williams",
      userPhoneNumber: "567-890-1234",
      emailAddress: "david.williams@example.com",
      sex: "Male",
      age: 28,
      highestLevelOfEducation: "Associate Degree",
      yearlyIncome: 58000,
      eventChoice: "Sporting Event",
    },
    {
      userId: "u1v2w3x4",
      userName: "Susan Brown",
      userPhoneNumber: "678-901-2345",
      emailAddress: "susan.brown@example.com",
      sex: "Female",
      age: 39,
      highestLevelOfEducation: "Bachelor's Degree",
      yearlyIncome: 92000,
      eventChoice: "Music Concert",
    },
    {
      userId: "y5z6a7b8",
      userName: "Michael Miller",
      userPhoneNumber: "789-012-3456",
      emailAddress: "michael.miller@example.com",
      sex: "Male",
      age: 48,
      highestLevelOfEducation: "Master's Degree",
      yearlyIncome: 115000,
      eventChoice: "Theatrical Performance",
    },
    {
      userId: "c9d0e1f2",
      userName: "Jennifer Davis",
      userPhoneNumber: "890-123-4567",
      emailAddress: "jennifer.davis@example.com",
      sex: "Female",
      age: 19,
      highestLevelOfEducation: "High School Diploma",
      yearlyIncome: 32000,
      eventChoice: "Comedy Show",
    },
    {
      userId: "g3h4i5j6",
      userName: "Robert Garcia",
      userPhoneNumber: "901-234-5678",
      emailAddress: "robert.garcia@example.com",
      sex: "Male",
      age: 62,
      highestLevelOfEducation: "PhD",
      yearlyIncome: 148000,
      eventChoice: "Sporting Event",
    },
    {
      userId: "k7l8m9n0",
      userName: "Linda Rodriguez",
      userPhoneNumber: "012-345-6789",
      emailAddress: "linda.rodriguez@example.com",
      sex: "Female",
      age: 31,
      highestLevelOfEducation: "Associate Degree",
      yearlyIncome: 61000,
      eventChoice: "Music Concert",
    },
    {
      userId: "o1p2q3r4",
      userName: "William Martinez",
      userPhoneNumber: "123-456-7891",
      emailAddress: "william.martinez@example.com",
      sex: "Male",
      age: 41,
      highestLevelOfEducation: "Bachelor's Degree",
      yearlyIncome: 98000,
      eventChoice: "Theatrical Performance",
    },
    {
      userId: "s5t6u7v8",
      userName: "Elizabeth Hernandez",
      userPhoneNumber: "234-567-8902",
      emailAddress: "elizabeth.hernandez@example.com",
      sex: "Female",
      age: 55,
      highestLevelOfEducation: "Master's Degree",
      yearlyIncome: 125000,
      eventChoice: "Comedy Show",
    },
    {
      userId: "w9x0y1z2",
      userName: "James Lopez",
      userPhoneNumber: "345-678-9013",
      emailAddress: "james.lopez@example.com",
      sex: "Male",
      age: 25,
      highestLevelOfEducation: "High School Diploma",
      yearlyIncome: 48000,
      eventChoice: "Sporting Event",
    },
    {
      userId: "a3b4c5d6",
      userName: "Patricia Gonzalez",
      userPhoneNumber: "456-789-0124",
      emailAddress: "patricia.gonzalez@example.com",
      sex: "Female",
      age: 59,
      highestLevelOfEducation: "PhD",
      yearlyIncome: 155000,
      eventChoice: "Music Concert",
    },
    {
      userId: "e7f8g9h0",
      userName: "Christopher Perez",
      userPhoneNumber: "567-890-1235",
      emailAddress: "christopher.perez@example.com",
      sex: "Male",
      age: 29,
      highestLevelOfEducation: "Associate Degree",
      yearlyIncome: 65000,
      eventChoice: "Theatrical Performance",
    },
  ],
};
